package dns

import (
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/wemit/domloc/internal/platform"
)

const dnsmasqPort = 5300

const dnsmasqConfTemplate = `# Generated by domloc — do not edit manually
port={{.Port}}
listen-address=127.0.0.1
bind-interfaces
no-resolv
{{range .TLDs}}
address=/.{{.}}/127.0.0.1
{{end}}
`

type dnsmasqConf struct {
	Port int
	TLDs []string
}

func confPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "domloc", "dnsmasq.conf")
}

func agentPlistPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, "Library", "LaunchAgents", "com.domloc.dnsmasq.plist")
}

const agentPlistTemplate = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.domloc.dnsmasq</string>
	<key>ProgramArguments</key>
	<array>
		<string>{{.DnsmasqBin}}</string>
		<string>--no-daemon</string>
		<string>--conf-file={{.ConfFile}}</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>KeepAlive</key>
	<true/>
	<key>StandardOutPath</key>
	<string>{{.LogFile}}</string>
	<key>StandardErrorPath</key>
	<string>{{.LogFile}}</string>
</dict>
</plist>
`

type agentPlistData struct {
	DnsmasqBin string
	ConfFile   string
	LogFile    string
}

func ConfigureTLD(tld string) error {
	tlds, err := loadTLDs()
	if err != nil {
		return err
	}
	for _, t := range tlds {
		if t == tld {
			return nil
		}
	}
	tlds = append(tlds, tld)
	return writeDnsmasqConf(tlds)
}

func IsTLDConfigured(tld string) bool {
	tlds, err := loadTLDs()
	if err != nil {
		return false
	}
	for _, t := range tlds {
		if t == tld {
			return true
		}
	}
	return false
}

func writeDnsmasqConf(tlds []string) error {
	tmpl, err := template.New("dnsmasq").Parse(dnsmasqConfTemplate)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(confPath()), 0755); err != nil {
		return err
	}
	f, err := os.Create(confPath())
	if err != nil {
		return err
	}
	defer f.Close()
	return tmpl.Execute(f, dnsmasqConf{Port: dnsmasqPort, TLDs: tlds})
}

func loadTLDs() ([]string, error) {
	data, err := os.ReadFile(confPath())
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var tlds []string
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "address=/.") {
			parts := strings.Split(line, "/")
			if len(parts) >= 2 {
				tlds = append(tlds, strings.TrimPrefix(parts[1], "."))
			}
		}
	}
	return tlds, nil
}

func InstallAgent() error {
	bin, err := findDnsmasq()
	if err != nil {
		return err
	}
	home, _ := os.UserHomeDir()
	logFile := filepath.Join(home, ".config", "domloc", "dnsmasq.log")

	tmpl, err := template.New("agent").Parse(agentPlistTemplate)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(agentPlistPath()), 0755); err != nil {
		return err
	}
	f, err := os.Create(agentPlistPath())
	if err != nil {
		return err
	}
	defer f.Close()
	if err := tmpl.Execute(f, agentPlistData{
		DnsmasqBin: bin,
		ConfFile:   confPath(),
		LogFile:    logFile,
	}); err != nil {
		return err
	}

	_, _ = platform.RunCommand("launchctl", "unload", agentPlistPath())
	_, err = platform.RunCommand("launchctl", "load", "-w", agentPlistPath())
	if err != nil {
		return fmt.Errorf("launchctl load agent: %w", err)
	}
	return waitForDNS(5 * time.Second)
}

func RestartAgent() error {
	_, _ = platform.RunCommand("launchctl", "unload", agentPlistPath())
	_, err := platform.RunCommand("launchctl", "load", "-w", agentPlistPath())
	if err != nil {
		return fmt.Errorf("launchctl reload agent: %w", err)
	}
	return waitForDNS(5 * time.Second)
}

func InstallResolver(tld string) error {
	resolverDir, err := platform.ResolverDir()
	if err != nil {
		return err
	}
	resolverFile := filepath.Join(resolverDir, tld)
	content := fmt.Sprintf("nameserver 127.0.0.1\nport %d\n", dnsmasqPort)

	if existing, err := os.ReadFile(resolverFile); err == nil && string(existing) == content {
		return nil
	}

	tmp, err := os.CreateTemp("", "domloc-resolver-*")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.WriteString(content); err != nil {
		return err
	}
	tmp.Close()

	if err := os.MkdirAll(resolverDir, 0755); err != nil {
		if err2 := platform.RunSudo("mkdir", "-p", resolverDir); err2 != nil {
			return err2
		}
	}
	return platform.RunSudo("cp", tmp.Name(), resolverFile)
}

func ConfigureTLDForDomain(domain string) (changed bool, err error) {
	parts := strings.Split(strings.TrimPrefix(domain, "*."), ".")
	tld := parts[len(parts)-1]

	if IsTLDConfigured(tld) {
		return false, nil
	}

	if err := ConfigureTLD(tld); err != nil {
		return false, err
	}
	if err := InstallResolver(tld); err != nil {
		return false, err
	}
	if err := RestartAgent(); err != nil {
		return false, err
	}
	return true, nil
}

func IsInstalled() bool {
	return platform.CommandExists("dnsmasq")
}

func IsAgentRunning() bool {
	out, err := platform.RunCommand("launchctl", "list", "com.domloc.dnsmasq")
	return err == nil && strings.Contains(out, "com.domloc.dnsmasq")
}

func Install() error {
	_, err := platform.RunCommand("brew", "install", "dnsmasq")
	return err
}

func ValidateResolution(domain string) error {
	out, err := platform.RunCommand("dig", "+short",
		fmt.Sprintf("-p%d", dnsmasqPort), domain, "@127.0.0.1")
	if err != nil {
		return fmt.Errorf("dig failed: %w", err)
	}
	if !strings.Contains(out, "127.0.0.1") {
		return fmt.Errorf("%s does not resolve to 127.0.0.1 (got %q)", domain, out)
	}
	return nil
}

func waitForDNS(timeout time.Duration) error {
	deadline := time.Now().Add(timeout)
	addr := fmt.Sprintf("127.0.0.1:%d", dnsmasqPort)
	for time.Now().Before(deadline) {
		conn, err := net.DialTimeout("udp", addr, 200*time.Millisecond)
		if err == nil {
			conn.Close()
			return nil
		}
		time.Sleep(200 * time.Millisecond)
	}
	return fmt.Errorf("dnsmasq did not start within %s", timeout)
}

func findDnsmasq() (string, error) {
	out, err := platform.RunCommand("which", "dnsmasq")
	if err != nil || strings.TrimSpace(out) == "" {
		prefix := platform.HomebrewPrefix()
		candidate := filepath.Join(prefix, "sbin", "dnsmasq")
		if _, err := os.Stat(candidate); err == nil {
			return candidate, nil
		}
		return "", fmt.Errorf("dnsmasq not found")
	}
	return strings.TrimSpace(out), nil
}
