package caddy

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/wemit/domloc/internal/platform"
	"github.com/wemit/domloc/internal/registry"
	"github.com/wemit/domloc/internal/services"
)

const (
	adminAPI   = "http://localhost:2019"
	serverName = "domloc"
)

const caddyfileTemplate = `# Generated by domloc — do not edit manually
{
	storage file_system {
		root {{.DataDir}}
	}
}
{{range .Routes}}
{{if .HTTPS}}{{.Domain}}{{else}}http://{{.Domain}}{{end}} {
	reverse_proxy localhost:{{.Port}}
{{if .HTTPS}}	tls internal
{{end}}}
{{end}}
`

type serverConfig struct {
	Listen []string      `json:"listen"`
	Routes []routeConfig `json:"routes"`
}

type routeConfig struct {
	Match    []matchConfig  `json:"match"`
	Handle   []handleConfig `json:"handle"`
	Terminal bool           `json:"terminal"`
}

type matchConfig struct {
	Host []string `json:"host"`
}

type handleConfig struct {
	Handler   string     `json:"handler"`
	Upstreams []upstream `json:"upstreams,omitempty"`
}

type upstream struct {
	Dial string `json:"dial"`
}

func configDir() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "domloc")
}

func CaddyfilePath() string {
	return filepath.Join(configDir(), "Caddyfile")
}

func Generate(routes []registry.Route) error {
	tmpl, err := template.New("caddyfile").Parse(caddyfileTemplate)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	dataDir := filepath.Join(configDir(), "caddy-data")
	if err := os.MkdirAll(dataDir, 0755); err != nil {
		return fmt.Errorf("create caddy data dir: %w", err)
	}

	path := CaddyfilePath()
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create Caddyfile: %w", err)
	}
	defer f.Close()

	type data struct {
		DataDir string
		Routes  []registry.Route
	}
	return tmpl.Execute(f, data{DataDir: dataDir, Routes: routes})
}

func EnsureRoutes(routes []registry.Route) error {
	if err := Generate(routes); err != nil {
		return err
	}

	if IsAdminAPIRunning() {
		if services.IsInstalled() {
			return services.Reload(CaddyfilePath())
		}
		return injectViaAPI(routes)
	}

	return services.Install(CaddyfilePath())
}

func Stop() error {
	if services.IsRunning() {
		return services.Uninstall()
	}
	return deleteServerFromAPI()
}

func IsRunning() bool {
	return services.IsRunning() || func() bool {
		out, err := platform.RunCommand("pgrep", "-x", "caddy")
		return err == nil && strings.TrimSpace(out) != ""
	}()
}

func IsAdminAPIRunning() bool {
	client := &http.Client{Timeout: 500 * time.Millisecond}
	resp, err := client.Get(adminAPI + "/config/")
	if err != nil {
		return false
	}
	resp.Body.Close()
	return resp.StatusCode == 200
}

func IsInstalled() bool {
	return platform.CommandExists("caddy")
}

func Install() error {
	_, err := platform.RunCommand("brew", "install", "caddy")
	return err
}

func TrustLocalCA() error {
	_, err := platform.RunCommand("caddy", "trust")
	return err
}

func ValidateConfig() error {
	_, err := platform.RunCommand("caddy", "validate", "--config", CaddyfilePath())
	return err
}

func injectViaAPI(routes []registry.Route) error {
	cfg := buildServerConfig(routes)
	body, err := json.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("marshal server config: %w", err)
	}

	url := fmt.Sprintf("%s/config/apps/http/servers/%s", adminAPI, serverName)
	req, err := http.NewRequest(http.MethodPut, url, bytes.NewReader(body))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{Timeout: 5 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("admin API request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("admin API returned %d", resp.StatusCode)
	}
	return nil
}

func deleteServerFromAPI() error {
	url := fmt.Sprintf("%s/config/apps/http/servers/%s", adminAPI, serverName)
	req, err := http.NewRequest(http.MethodDelete, url, nil)
	if err != nil {
		return err
	}
	client := &http.Client{Timeout: 5 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return err
	}
	resp.Body.Close()
	return nil
}

func buildServerConfig(routes []registry.Route) serverConfig {
	var rr []routeConfig
	for _, r := range routes {
		rr = append(rr, routeConfig{
			Match: []matchConfig{{Host: []string{r.Domain}}},
			Handle: []handleConfig{{
				Handler:   "reverse_proxy",
				Upstreams: []upstream{{Dial: fmt.Sprintf("localhost:%d", r.Port)}},
			}},
			Terminal: true,
		})
	}
	return serverConfig{
		Listen: []string{":443", ":80"},
		Routes: rr,
	}
}
